### ISSUE TITLE
[DataBus] StorageException with status code 412

### ISSUE THREAD

**Issue by Efp95** [rebus-org/Rebus.AzureBlobs#3]
Version: 0.1.0

### Issue

Hi, I'm having this exact same issue described [here](https://github.com/rebus-org/Rebus.AzureStorage/issues/10)

It's happening like twice a day and the blobs are still present in my blob container.

**HttpStatusCode:** 412
**HttpStatusMessage:** The condition specified using HTTP conditional header(s) is not met.
**ErrorCode:** ConditionNotMet
**ErrorMessage:** ErrorMessage: The condition specified using HTTP conditional header(s) is not met.
RequestId:7063d79d-c01e-000a-31fe-dcb1ae000000
Time:2020-02-06T15:00:07.6518868Z

**Comment by mookid8000** [comment]
I added a comment [here](https://github.com/rebus-org/Rebus.AzureStorage/issues/10#issuecomment-583297720), describing the issue.

I can probably fix this within the next couple of days, although PR is also welcome.

**Comment by mookid8000** [comment]
Could you try Rebus.AzureBlobs 0.5.0 and see if it's been fixed? (I think it is 🙂 )
