### ISSUE TITLE
Deprecated package

### ISSUE THREAD

**Issue by DCompagner** [rebus-org/Rebus.AzureBlobs#4]
Hi, the 'Microsoft.Azure.KeyVault.Core' package included in this project is deprecated.
Would you kindly upgrade to to a newer package, the package deprecation notice recommends Azure.Security.KeyVault.Secrets?

**Comment by mookid8000** [comment]
Sure, I've pushed  Rebus.AzureBlobs 0.6.0 to NuGet.org just now 🙂 

Thanks for makine me aware of this.

**Comment by DCompagner** [comment]
Thanks for the fast response. This is however not exactly what I meant, 
the whole 'Microsoft.Azure.KeyVault.Core' package is set as deprecated see: https://www.nuget.org/packages/Microsoft.Azure.KeyVault.Core

Can you upgrade to the appropriate package?

**Comment by mookid8000** [comment]
Microsoft.Azure.KeyVault.Core is deprecated, so one should not start new projects with it – but it's still receiving security fixes, so one should be afraid of having it included.

Changing to Azure.Security.KeyVault.Secrets requires that the Microsoft.Azure.Storage.Blob dependency be changed to Azure.Storage.Blobs, which is a bigger change.

It's definitely going to happen, but I don't have the time right now.

If you'd like to accelerate this, feel free to submit a PR 🙂 If you need help getting started doing the migration, I'd be happy to guide you
